//! Commit message and pull request rules (see CONTRIBUTING.md).

const TYPES: &[&str] = &["feat", "fix", "perf", "refactor", "docs", "test", "build", "ci", "style", "chore", "revert"];

/// Why a commit message breaks the rules, or None when it follows them.
/// Lines starting with `#` are git's comments and are ignored.
pub fn commit_problem(msg: &str) -> Option<String> {
    let msg: String = msg.lines().filter(|l| !l.starts_with('#')).collect::<Vec<_>>().join("\n");
    let subject = msg.lines().next().unwrap_or("");
    if subject.starts_with("Merge ") || subject.starts_with("Revert \"") {
        return None;
    }
    if !conventional(subject) {
        return Some(format!(
            "✗ not a Conventional Commit: \"{subject}\"\n  \
             expected: type(scope): lower-case imperative summary, no full stop\n  \
             types: {}",
            TYPES.join(", ")
        ));
    }
    let len = subject.chars().count();
    if len > 72 {
        return Some(format!("✗ subject is {len} characters; keep it to 72"));
    }
    if has_attribution(&msg) {
        return Some("✗ remove tool attribution; you are the author of this change".into());
    }
    None
}

/// `type(scope)!: description`, where the description starts with neither a
/// capital nor a space and doesn't end with a full stop.
fn conventional(subject: &str) -> bool {
    let Some(ty) = TYPES.iter().find(|t| subject.starts_with(*t)) else { return false };
    let mut rest = &subject[ty.len()..];
    if let Some(r) = rest.strip_prefix('(') {
        let Some(end) = r.find(')') else { return false };
        let scope = &r[..end];
        if scope.is_empty()
            || !scope.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || "._/-".contains(c))
        {
            return false;
        }
        rest = &r[end + 1..];
    }
    let rest = rest.strip_prefix('!').unwrap_or(rest);
    let Some(desc) = rest.strip_prefix(": ") else { return false };
    let Some(first) = desc.chars().next() else { return false };
    desc.chars().count() >= 2 && !first.is_ascii_uppercase() && first != ' ' && !desc.ends_with('.')
}

/// Lines that credit a tool rather than a person.
pub fn has_attribution(text: &str) -> bool {
    let t = text.to_lowercase();
    if t.contains("generated with ") || t.contains("generated by ") || t.contains('🤖') {
        return true;
    }
    if word(&t, "claude code") || t.match_indices("as an ai").any(|(i, m)| !word_char(t[i + m.len()..].chars().next()))
    {
        return true;
    }
    t.match_indices("co-authored-by:").any(|(i, m)| {
        let who = t[i + m.len()..].trim_start_matches(' ');
        ["claude", "copilot", "chatgpt", "gpt", "gemini", "cursor", "codex"].iter().any(|n| who.starts_with(n))
    })
}

fn word_char(c: Option<char>) -> bool {
    c.is_some_and(|c| c.is_alphanumeric() || c == '_')
}

/// `needle` with a word boundary on each side.
fn word(hay: &str, needle: &str) -> bool {
    hay.match_indices(needle)
        .any(|(i, m)| !word_char(hay[..i].chars().next_back()) && !word_char(hay[i + m.len()..].chars().next()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn subjects() {
        for ok in [
            "feat: add x",
            "fix(llm): retry an overload",
            "feat(cloud)!: drop the python launcher",
            "docs(demo/shop): explain",
            "Merge branch 'main'",
            "Revert \"feat: x\"",
            "# a comment\nfix: add y",
        ] {
            assert_eq!(commit_problem(ok), None, "{ok}");
        }
        for bad in ["Fix: x", "fix: Add x", "fix: add x.", "fix:add x", "fix(LLM): x", "wip", "fix():  x", "feat:  x"] {
            assert!(commit_problem(bad).is_some(), "{bad}");
        }
        assert!(commit_problem(&format!("fix: {}", "a".repeat(70))).unwrap().contains("75 characters"));
    }

    #[test]
    fn attribution() {
        for bad in [
            "fix: add x\n\nGenerated with a tool",
            "fix: add x\n\nCo-Authored-By: Claude Opus <noreply@anthropic.com>",
            "fix: add x\n\nco-authored-by:   gpt-5",
            "fix: add x\n\nmade in Claude Code.",
            "fix: add x\n\nAs an AI, I",
            "fix: add x 🤖",
        ] {
            assert!(commit_problem(bad).is_some(), "{bad}");
        }
        for ok in [
            "fix: add x\n\nCo-authored-by: Ada <ada@example.com>",
            "fix: add x\n\nclaude codes",
            "fix: add x\n\nas an aim",
        ] {
            assert_eq!(commit_problem(ok), None, "{ok}");
        }
    }
}
